[build]
  base = "apps/frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"

[[redirects]]
  from = "/profile-craft/*"
  to = "/profile-craft/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/profile-craft/"
  status = 301

[[headers]]
  for = "/profile-craft/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
